name: Build and Publish Sneaklardooon Docker Image

on:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '0 4 * * 6'

  push:
    branches: [main]

  workflow_dispatch:

jobs:
  Build-Sneaklardooon-binaries-Docker-image:
    name: Build Sneaklardooon binaries Docker image and push to Github and Dockerhub
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Login to Github Packages
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Get current date
          id: date
          run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

        - name: Build image and push to Docker Hub and GitHub Container Registry
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
              aterfax/sneaklardooon:latest 
              ghcr.io/aterfax/sneaklardooon:latest
              aterfax/sneaklardooon:${{ env.DATE }}
              ghcr.io/aterfax/sneaklardooon:${{ env.DATE }}

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
